[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "rpath"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "rpath"]

[target.aarch64-unknown-linux-gnu]
rustflags = ["-C", "rpath"]
linker = "aarch64-unknown-linux-gnu-gcc"
